//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MITD.Fuel.Integration.VesselReportManagementSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPMInfo
    {
        public int ID { get; set; }
        public Nullable<int> DraftID { get; set; }
        public Nullable<int> ShipID { get; set; }
        public string ConsNo { get; set; }
        public string ShipName { get; set; }
        public string VoyageNo { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Day { get; set; }
        public string PortName { get; set; }
        public Nullable<double> PortTime { get; set; }
        public Nullable<double> AtSeaLatitudeDegree { get; set; }
        public Nullable<double> AtSeaLatitudeMinute { get; set; }
        public Nullable<double> AtSeaLongitudeDegree { get; set; }
        public Nullable<double> AtSeaLongitudeMinute { get; set; }
        public Nullable<double> ObsDist { get; set; }
        public Nullable<double> EngDist { get; set; }
        public double SteamTime { get; set; }
        public decimal AvObsSpeed { get; set; }
        public Nullable<double> AvEngSpeed { get; set; }
        public int RPM { get; set; }
        public Nullable<double> Slip { get; set; }
        public Nullable<double> WindDir { get; set; }
        public Nullable<double> WindForce { get; set; }
        public Nullable<double> SeaDir { get; set; }
        public Nullable<double> SeaForce { get; set; }
        public Nullable<double> ROBHO { get; set; }
        public Nullable<double> ROBDO { get; set; }
        public Nullable<double> ROBMGO { get; set; }
        public Nullable<double> ROBFW { get; set; }
        public Nullable<double> ConsInPortHO { get; set; }
        public Nullable<double> ConsInPortDO { get; set; }
        public Nullable<double> ConsInPortMGO { get; set; }
        public Nullable<double> ConsInPortFW { get; set; }
        public double ConsAtSeaHO { get; set; }
        public Nullable<double> ConsAtSeaDO { get; set; }
        public Nullable<double> ConsAtSeaMGO { get; set; }
        public Nullable<double> ConsAtSeaFW { get; set; }
        public Nullable<double> ReceivedHO { get; set; }
        public Nullable<double> ReceivedDO { get; set; }
        public Nullable<double> ReceivedMGO { get; set; }
        public Nullable<double> ReceivedFW { get; set; }
        public string ETAPort { get; set; }
        public string ETADate { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public System.DateTime DateIn { get; set; }
        public double DailyFuelCons { get; set; }
        public decimal Speed { get; set; }
        public bool IsSM { get; set; }
        public string InPortOrAtSea { get; set; }
        public string ImportDate { get; set; }
        public Nullable<decimal> TransferHo { get; set; }
        public Nullable<decimal> TransferDo { get; set; }
        public Nullable<decimal> TransferFW { get; set; }
        public Nullable<decimal> TransferMGOLS { get; set; }
        public Nullable<decimal> CorrectionHo { get; set; }
        public Nullable<decimal> CorrectionDo { get; set; }
        public Nullable<decimal> CorrectionFW { get; set; }
        public Nullable<decimal> CorrectionMGOLS { get; set; }
        public Nullable<bool> CorrectionTypeHo { get; set; }
        public Nullable<bool> CorrectionTypeDo { get; set; }
        public Nullable<bool> CorrectionTypeFW { get; set; }
        public Nullable<bool> CorrectionTypeMGOLS { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public Nullable<byte> FuelRepotType { get; set; }
        public Nullable<int> State { get; set; }
    
        public virtual Ship Ship { get; set; }
    }
}
