//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MITD.Fuel.Integration.VesselReportManagementSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ship
    {
        public Ship()
        {
            this.RPMInfoes = new HashSet<RPMInfo>();
        }
    
        public int ID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public string Name { get; set; }
        public string ShipID { get; set; }
        public Nullable<int> DepartmentID_FK { get; set; }
    
        public virtual ICollection<RPMInfo> RPMInfoes { get; set; }
    }
}
