//------------------------------------------------------------------------------
// This is auto-generated VoyageNumber.
//------------------------------------------------------------------------------
// This VoyageNumber was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// VoyageNumber is generated on: 8/20/2013 12:22:04 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the VoyageNumber is regenerated.
//------------------------------------------------------------------------------

#region

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;

#endregion

namespace MITD.Fuel.Domain.Model.DomainObjects
{
    /// <summary>
    /// There are no comments for MITD.Fuel.Domain.Model.DomainObjects.Voyage in the schema.
    /// </summary>
    public class VoyageLog
    {
        public VoyageLog()
        {
        }

        public VoyageLog(
            long id,
            long referencedVoyageId,
            DateTime changeDate,
            string voyageNumber,
            string description,
            VesselInCompany vesselInCompany,
            Company company,
            DateTime startDate,
            DateTime endDate,
            bool isActive)
        {
            Id = id;
            ReferencedVoyageId = referencedVoyageId;
            ChangeDate = changeDate;
            VoyageNumber = voyageNumber;
            Description = description;
            this.VesselInCompany = vesselInCompany;
            Company = company;
            StartDate = startDate;
            EndDate = endDate;
            IsActive = isActive;

        }

        public long Id { get; private set; }
        public long ReferencedVoyageId { get; private set; }
        public DateTime ChangeDate { get; private set; }
        public string VoyageNumber { get; private set; }
        public string Description { get; private set; }

        //public long VesselInCompanyId { get; private set; }
        //public long CompanyId { get; private set; }
        public DateTime StartDate { get; private set; }
        public DateTime EndDate { get; private set; }
        public bool IsActive { get; private set; }
        public virtual VesselInCompany VesselInCompany { get; private set; }
        public virtual Company Company { get; private set; }

        public virtual Voyage ReferencedVoyage { get; private set; }

        public long CompanyId { get; private set; }

        public long VesselInCompanyId { get; private set; }
    }
}